blank_issues_enabled: false
contact_links:
  - name: Pyro Discussion Forum
    url: https://forum.pyro.ai/
    about: For general questions about NumPyro, please use the forum instead of GitHub issues.
